/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yalung_program;

import java.awt.event.ActionEvent;

/**
 *
 * @author Administrator
 */
public class AdminDashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboardForm.class.getName());

    /**
     * Creates new form AdminDashboardForm
     */
    public AdminDashboardForm() {
        initComponents();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cmbCourse = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel1.setText("Course:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 75, 27));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 75, 27));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 75, 27));

        txtFirstname.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 40));

        txtLastname.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 190, 40));

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 100, 40));

        btnAdd.setBackground(new java.awt.Color(102, 153, 0));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 40));

        btnUpdate.setBackground(new java.awt.Color(0, 102, 204));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, 40));

        btnDelete.setBackground(new java.awt.Color(102, 0, 51));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 100, 40));

        btnClear.setBackground(new java.awt.Color(153, 153, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 100, 40));

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HM", "BSOA", "ACT", " " }));
        cmbCourse.addActionListener(this::cmbCourseActionPerformed);
        jPanel1.add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("First name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 75, 27));

        tblStudents.setAutoCreateRowSorter(true);
        tblStudents.setBackground(new java.awt.Color(255, 204, 204));
        tblStudents.setForeground(new java.awt.Color(0, 0, 0));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Course"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 370, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
String firstName = txtFirstname.getText().trim();
    String lastName = txtLastname.getText().trim();
    String course = cmbCourse.getSelectedItem().toString();

    if (firstName.isEmpty() || lastName.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        java.sql.Connection conn = DBConnection.connect();
        String sql = "INSERT INTO Students (First_Name, Last_Name, Course) VALUES (?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, firstName);
        pst.setString(2, lastName);
        pst.setString(3, course);

        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Student added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        conn.close();
        loadTableData();
        btnClearActionPerformed(evt);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
   int selectedRow = tblStudents.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table to update!", "Selection Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Kukunin ang Student_ID sa Column 0 ng napiling row sa table
    String studentId = tblStudents.getValueAt(selectedRow, 0).toString();

    try {
        java.sql.Connection conn = DBConnection.connect();
        String sql = "UPDATE Students SET First_Name=?, Last_Name=?, Course=? WHERE Student_ID=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtFirstname.getText().trim());
        pst.setString(2, txtLastname.getText().trim());
        pst.setString(3, cmbCourse.getSelectedItem().toString());
        pst.setString(4, studentId);

        pst.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Student record updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        conn.close();
        loadTableData();
        btnClearActionPerformed(evt);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     int selectedRow = tblStudents.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table to delete!", "Selection Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Kukunin ang Student_ID sa Column 0 ng napiling row sa table
    String studentId = tblStudents.getValueAt(selectedRow, 0).toString();

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this student record?", "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection conn = DBConnection.connect();
            String sql = "DELETE FROM Students WHERE Student_ID=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, studentId);

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Student record deleted from database!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            conn.close();
            loadTableData();
            btnClearActionPerformed(evt);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

    txtFirstname.setText("");
    txtLastname.setText("");
    cmbCourse.setSelectedIndex(0);
    tblStudents.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    Roleform role = new Roleform();
    role.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblStudents.getModel();
        int selectedRow = tblStudents.getSelectedRow();

        if (selectedRow != -1) {

            txtFirstname.setText(model.getValueAt(selectedRow, 1).toString());
            txtLastname.setText(model.getValueAt(selectedRow, 2).toString());
            cmbCourse.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
        }
    }//GEN-LAST:event_tblStudentsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboardForm().setVisible(true));
    }
 private void loadTableData() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblStudents.getModel();
    model.setRowCount(0);

    try {
        java.sql.Connection conn = DBConnection.connect();
        String sql = "SELECT * FROM Students";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("Student_ID"),
                rs.getString("First_Name"),
                rs.getString("Last_Name"),
                rs.getString("Course")
            });
        }
        conn.close();
    } catch (Exception e) {
        System.out.println("Error loading table: " + e.getMessage());
    }
}   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables

}
