/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yalung_program;

/**
 *
 * @author CL2-PC
 */
public class RBS_Form extends javax.swing.JFrame {

    /**
     * Creates new form RBS_Form
     */
    public RBS_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        Trigonometry = new javax.swing.JComboBox<>();
        Trigonometry1 = new javax.swing.JComboBox<>();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jLabel6.setText("____");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("______");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, -1, 0));

        jButton2.setBackground(new java.awt.Color(255, 204, 153));
        jButton2.setText("xʸ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 427, 64, 34));

        jButton3.setBackground(new java.awt.Color(255, 204, 153));
        jButton3.setText("x²");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 347, 64, 34));

        jButton4.setBackground(new java.awt.Color(255, 204, 153));
        jButton4.setText("2nd");
        jButton4.setToolTipText("");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 307, 64, 34));

        jButton5.setBackground(new java.awt.Color(255, 204, 153));
        jButton5.setText("10ˣ");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 467, 64, 34));

        jButton6.setBackground(new java.awt.Color(255, 204, 153));
        jButton6.setText("log");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 507, 64, 34));

        jButton7.setBackground(new java.awt.Color(255, 204, 153));
        jButton7.setText("²√x");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 387, 64, 34));

        jButton8.setBackground(new java.awt.Color(255, 204, 153));
        jButton8.setText("In");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 547, 64, 34));

        jButton9.setBackground(new java.awt.Color(255, 204, 153));
        jButton9.setText("1/x");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 347, 64, 34));

        jButton10.setBackground(new java.awt.Color(255, 204, 153));
        jButton10.setText("π ");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 307, 64, 34));

        jButton11.setText("4");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 467, 64, 34));

        jButton12.setText("1");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 507, 64, 34));

        jButton13.setBackground(new java.awt.Color(255, 204, 153));
        jButton13.setText("(");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 387, 64, 34));

        jButton14.setText("+/−");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 547, 64, 34));

        jButton15.setText("7");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 427, 64, 34));

        jButton16.setBackground(new java.awt.Color(255, 204, 153));
        jButton16.setText("|x|");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 347, 64, 34));

        jButton17.setBackground(new java.awt.Color(255, 204, 153));
        jButton17.setText("e");
        jButton17.setToolTipText("");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 307, 64, 34));

        jButton18.setText("5");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 467, 64, 34));

        jButton19.setText("2");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 507, 64, 34));

        jButton20.setBackground(new java.awt.Color(255, 204, 153));
        jButton20.setText(")");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 387, 64, 34));

        jButton21.setText("0");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 547, 64, 34));

        jButton22.setText("8");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 427, 64, 34));

        jButton23.setBackground(new java.awt.Color(255, 204, 153));
        jButton23.setText("exp");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 347, 64, 34));

        jButton24.setBackground(new java.awt.Color(255, 204, 153));
        jButton24.setText("C");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 307, 64, 34));

        jButton25.setText("6");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 467, 64, 34));

        jButton26.setText("3");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 507, 64, 34));

        jButton27.setBackground(new java.awt.Color(255, 204, 153));
        jButton27.setText("n!");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 387, 64, 34));

        jButton28.setText(".");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 547, 64, 34));

        jButton29.setText("9");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 427, 64, 34));

        jButton30.setBackground(new java.awt.Color(255, 204, 153));
        jButton30.setText("mod");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 347, 64, 34));

        jButton31.setBackground(new java.awt.Color(255, 204, 153));
        jButton31.setText("⌫");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 307, 64, 34));

        jButton32.setBackground(new java.awt.Color(255, 204, 153));
        jButton32.setText("-");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 467, 64, 34));

        jButton33.setBackground(new java.awt.Color(255, 204, 153));
        jButton33.setText("+");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 507, 64, 34));

        jButton34.setBackground(new java.awt.Color(255, 204, 153));
        jButton34.setText("÷");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 387, 64, 34));

        jButton35.setBackground(new java.awt.Color(0, 204, 255));
        jButton35.setText("=");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 547, 64, 34));

        jButton36.setBackground(new java.awt.Color(255, 204, 153));
        jButton36.setText("X");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 427, 64, 34));

        Trigonometry.setBackground(new java.awt.Color(255, 204, 153));
        Trigonometry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trigonometry" }));
        Trigonometry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrigonometryActionPerformed(evt);
            }
        });
        getContentPane().add(Trigonometry, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 245, 180, 44));

        Trigonometry1.setBackground(new java.awt.Color(255, 204, 153));
        Trigonometry1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Function" }));
        Trigonometry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trigonometry1ActionPerformed(evt);
            }
        });
        getContentPane().add(Trigonometry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 245, 108, 44));

        jButton37.setText("M+");
        jButton37.setToolTipText("");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 187, 52, 34));

        jButton38.setText("MS⌄");
        jButton38.setToolTipText("");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 187, 50, 34));

        jButton39.setText("M-");
        jButton39.setToolTipText("");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 187, 54, 34));

        jButton40.setText("MR");
        jButton40.setToolTipText("");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 187, 52, 34));

        jButton41.setText("DEG");
        jButton41.setToolTipText("");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 135, 52, 34));

        jButton42.setText("MS");
        jButton42.setToolTipText("");
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 187, 50, 34));

        jButton43.setText("MC");
        jButton43.setToolTipText("");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 187, 52, 34));

        jButton44.setText("F-E");
        jButton44.setToolTipText("");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 135, 52, 34));

        jLabel5.setText("____");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel7.setText("____");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel8.setText("____");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SCIENTIFIC");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 230, 50));

        jLabel3.setText("🕘");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void TrigonometryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrigonometryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrigonometryActionPerformed

    private void Trigonometry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trigonometry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trigonometry1ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RBS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RBS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RBS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RBS_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RBS_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Trigonometry;
    private javax.swing.JComboBox<String> Trigonometry1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
