
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author CL2-PC
 */
public class CAFE extends javax.swing.JFrame {

    /**
     * Creates new form CAFE
     */
    public CAFE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label11 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        txtSnacksqty = new java.awt.TextField();
        label12 = new java.awt.Label();
        txtDrinksqty = new java.awt.TextField();
        label14 = new java.awt.Label();
        txtSnacks = new java.awt.TextField();
        btnProceed = new java.awt.Button();
        label15 = new java.awt.Label();
        txtDrinks = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        label13 = new java.awt.Label();
        txtChange = new java.awt.TextField();
        label16 = new java.awt.Label();
        txtsubtot = new java.awt.TextField();
        btnChange = new javax.swing.JButton();
        label17 = new java.awt.Label();
        txtCash = new java.awt.TextField();
        button2 = new java.awt.Button();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 0, 0));
        label4.setText("SNACKS");
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 0, 0));
        label5.setText("[2] Burger - 30");
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        label6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label6.setForeground(new java.awt.Color(0, 0, 0));
        label6.setText("[1] Fries");
        label6.setVisible(false);
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        label7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label7.setForeground(new java.awt.Color(0, 0, 0));
        label7.setText("DRINKS");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        label8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label8.setForeground(new java.awt.Color(0, 0, 0));
        label8.setText("[1] Fries - 25");
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        label9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label9.setForeground(new java.awt.Color(0, 0, 0));
        label9.setText(" [2] Tea - 20");
        jPanel2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        label11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 0, 0));
        label11.setText("[1] Coke - 15");
        jPanel2.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 570, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("CAFE MENU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 170, 50));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 0, 0));
        label10.setText("Quantity:");
        jPanel4.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        jPanel4.add(txtSnacksqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 190, 50));

        label12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label12.setForeground(new java.awt.Color(0, 0, 0));
        label12.setText("Snacks Choice:");
        jPanel4.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));
        jPanel4.add(txtDrinksqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 190, 50));

        label14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label14.setForeground(new java.awt.Color(0, 0, 0));
        label14.setText("Quantity:");
        jPanel4.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel4.add(txtSnacks, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 190, 50));

        btnProceed.setLabel("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });
        jPanel4.add(btnProceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 110, 50));

        label15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label15.setForeground(new java.awt.Color(0, 0, 0));
        label15.setText("Drinks Choice:");
        jPanel4.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
        jPanel4.add(txtDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 190, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 440, 440));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setText("ORDER INFO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 170, 50));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label13.setForeground(new java.awt.Color(0, 0, 0));
        label13.setText("Change:");
        jPanel6.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 40));
        jPanel6.add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 190, 50));

        label16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label16.setForeground(new java.awt.Color(0, 0, 0));
        label16.setText("Subtotal:");
        jPanel6.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel6.add(txtsubtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, 50));

        btnChange.setText("SUBMIT");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel6.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 90, 40));

        label17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label17.setForeground(new java.awt.Color(0, 0, 0));
        label17.setText("Cash:");
        jPanel6.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel6.add(txtCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, 50));

        button2.setLabel("ORDER AGAIN");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel6.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 390, 440));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("RECEIPT");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
      int Drinksprice = 0;
      int Snacksprice = 0;
      int Drinkqty = 0;
      int Snackqty = 0;
      
      
      if (!txtDrinks.getText().equals(""));
      int Drinkchoice = Integer.parseInt(txtDrinks.getText());
      Drinkqty = Integer.parseInt(txtDrinksqty.getText());
      
      if (Drinkchoice == 1) {
        Drinksprice = 15;
      }
      else if (Drinkchoice == 2) {
        Drinksprice = 20;   
      }
      
       if (!txtSnacks.getText().equals(""));
      int Snackchoice = Integer.parseInt(txtSnacks.getText());
      Snackqty = Integer.parseInt(txtSnacksqty.getText());
      
      if (Snackchoice == 1) {
        Snacksprice = 25;
      }
      else if (Snackchoice == 2) {
        Snacksprice = 30;   
      }
      
      
      int subtotal = (Drinksprice * Drinkqty) + (Snacksprice * Snackqty);
      txtsubtot.setText("" + subtotal);
      
      
    }//GEN-LAST:event_btnProceedActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
       
       try {
    int cash = Integer.parseInt(txtCash.getText().trim());
    int subtotal = Integer.parseInt(txtsubtot.getText().trim());
  
    while (cash < subtotal) {
        txtCash.setText("");
        JOptionPane.showMessageDialog(this, "Insufficient Cash, Input again!");
        
        
       
        String newCash = JOptionPane.showInputDialog(this, "Enter cash amount:");
        if (newCash == null) { // Kung cancel, stop na
            return;
        }

       
        try {
            cash = Integer.parseInt(newCash.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid number. Try again.");
            continue; 
        }
    }

   
    int change = cash - subtotal;
    txtChange.setText(String.valueOf(change));

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Please enter valid numbers for cash and subtotal.");
}
       
       
    }//GEN-LAST:event_btnChangeActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        txtDrinks.setText("");
        txtDrinksqty.setText("");
        txtSnacks.setText("");
        txtSnacksqty.setText("");
        txtsubtot.setText("");
        txtCash.setText("");
        txtChange.setText("");
    }//GEN-LAST:event_button2ActionPerformed

   
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAFE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private java.awt.Button btnProceed;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField txtCash;
    private java.awt.TextField txtChange;
    private java.awt.TextField txtDrinks;
    private java.awt.TextField txtDrinksqty;
    private java.awt.TextField txtSnacks;
    private java.awt.TextField txtSnacksqty;
    private java.awt.TextField txtsubtot;
    // End of variables declaration//GEN-END:variables
}
